#!/usr/bin/env python

import sys
from PIL import *

pdirectory = "~/Desktop/MissionFolder/tensortraining/TrainingImages/center"
base = "training"
count = 0
while(True):
	cistr = pdirectory
	#cimg = Image.open(base + str(count))
	width = img.size[0]
	height = img.size[1]
	cimg = cimg.crop(0, height/2, width, height/2)
	cimg.save(base + str(count))
	print(count)

		
	
