#!/bin/bash
vlc -I dummy http://192.168.0.65:8081/mjpg/video.mjpg --video-filter=scene --vout=dummy --scene-format=jpeg --scene-ratio=10 --scene-prefix=i --scene-replace --scene-path=/home/noc/Desktop/MissionFolder/Images/


